### ISSUE TITLE
error when running Run-time/mnist.py

### ISSUE THREAD

**Issue by fpeder** [MatthieuCourbariaux/BinaryNet#13]
This is what I got, (the training part works fine):

Using gpu device 0: GeForce GTX 960 (CNMeM is enabled with initial size: 90.0% of memory, cuDNN 5105)
Traceback (most recent call last):
  File "binary_ops.py", line 225, in <module>
    dot2 = theano.function([A,B], Gemm()(A, B))
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.9.0.dev4-py2.7.egg/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.9.0.dev4-py2.7.egg/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.9.0.dev4-py2.7.egg/theano/compile/function_module.py", line 1784, in orig_function
    defaults)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.9.0.dev4-py2.7.egg/theano/compile/function_module.py", line 1651, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.9.0.dev4-py2.7.egg/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.9.0.dev4-py2.7.egg/theano/gof/vm.py", line 1055, in make_all
    impl=impl))
TypeError: ('The following error happened while compiling the node', Gemm(GpuContiguous.0, GpuContiguous.0), '\n', "make_thunk() got an unexpected keyword argument 'impl'")

Thanks

**Comment by ruizhoud** [comment]
Exactly the same to me..

**Comment by fpeder** [comment]
Downgrading Theano to version 0.8.2 solved the problem to me

**Comment by ruizhoud** [comment]
Thanks, I solved it by not using "baseline" in the first layer, but using "theano".. (which I do not believe is really a solution)

**Comment by RoboEvangelist** [comment]
I'm having the same error. How did you downgrade? Did you have to uninstall and reinstall theano manually?

**Comment by fpeder** [comment]
I have just compiled Theano from source code choosing that version

2016-12-24 3:33 GMT+01:00 Luis Bill <notifications@github.com>:

**Comment by qigongsun** [comment]
Install Theano with version 0.8.0, this problem can be solved.
sudo pip install -r https://raw.githubusercontent.com/Lasagne/Lasagne/master/requirements.txt

**Comment by amanusk** [comment]
Doing that creates a new error 
('Wrong major API version for gpuarray:', 1, 'Make sure Theano and libgpuarray/pygpu are in sync.')
The error was not there with Theano 0.9.0
Any idea for a workaround?

**Comment by caiwenpu** [comment]
I use Theano with version 0.9.0 and I have sloved the problem by add an argument " impl='c' " in function make_thunk of class Gemm and class XnorGemm.
