### ISSUE TITLE
Permission denied when running mnist.py 

### ISSUE THREAD

**Issue by janarbek** [MatthieuCourbariaux/BinaryNet#14]
Hi All,

I am having following problem when I try to run mnist.py of training.  Anyone have any ideas ?

Thanks in advance for your help.

I am on Windows 7 using Anaconda. 

Using gpu device 0: Quadro K620 (CNMeM is disabled, cuDNN not available)
C:\Users\jmatai\AppData\Local\Continuum\Anaconda2\lib\site-packages\theano\tensor\signal\downsample.py:6: UserWarning: downsample module has been moved to the t
heano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
batch_size = 100
alpha = 0.1
epsilon = 0.0001
num_units = 4096
n_hidden_layers = 3
num_epochs = 1000
dropout_in = 0.2
dropout_hidden = 0.5
activation = binary_net.binary_tanh_unit
binary = True
stochastic = False
H = 1.0
W_LR_scale = Glorot
LR_start = 0.003
LR_fin = 3e-07
LR_decay = 0.990831944893
save_path = mnist_parameters.npz
shuffle_parts = 1
Loading MNIST dataset...
Traceback (most recent call last):
  File "mnist.py", line 93, in <module>
    train_set = MNIST(which_set= 'train', start=0, stop = 50000, center = False)
  File "c:\projects\python_packages\pylearn2\pylearn2\datasets\mnist.py", line 93, in __init__
    topo_view = read_mnist_images(im_path, dtype='float32')
  File "c:\projects\python_packages\pylearn2\pylearn2\utils\mnist_ubyte.py", line 94, in read_mnist_images
    with open_if_filename(fn, 'rb') as f:
  File "c:\projects\python_packages\pylearn2\pylearn2\utils\mnist_ubyte.py", line 46, in __enter__
    self._handle = open(self._f, self._mode, self._buffering)
**IOError: [Errno 13] Permission denied: 'C:\\projects\\repos\\dl\\data/mnist/train-images-idx3-ubyte'**

(C:\Users\jmatai\AppData\Local\Continuum\Anaconda2) C:\projects\repos\bnn\BinaryNet\Train-time>

**Comment by bruce1408** [comment]
you should better change you data path to D:\ or another disk.

**Comment by sam93katoch** [comment]
Hello,
I am facing the similar issue. Were you able to solve the problem?

Thanks in advance!

**Comment by chua4380** [comment]
but it does not work!!!
