### ISSUE TITLE
ImportError: No module named six.moves

### ISSUE THREAD

**Issue by JiyuFang-git** [MatthieuCourbariaux/BinaryNet#29]
I installed pylearn2 and theano(bleeding-edge version) following the links given on the README.
When running  mnist.py I encountered the following error:

Using cuDNN version 5005 on context None
Preallocating 3027/4036 Mb (0.750000) on cuda
Mapped name None to device cuda: GeForce GTX 970 (0000:0F:00.0)
Traceback (most recent call last):
  File "mnist.py", line 24, in <module>
    from pylearn2.datasets.mnist import MNIST
  File "/home/jiyu/fyp/pylearn2/pylearn2/__init__.py", line 4, in <module>
    from pylearn2.utils.logger import configure_custom
  File "/home/jiyu/fyp/pylearn2/pylearn2/utils/__init__.py", line 11, in <module>
    from theano.compat.six.moves import input, zip as izip
ImportError: No module named six.moves

I tried to solve the issue by installing Theano 0.8, but then a new problem occurred:

ERROR (theano.sandbox.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/jiyu/miniconda2/envs/py27/lib/python2.7/site-packages/theano/sandbox/gpuarray/__init__.py", line 95, in <module>
    init_dev(config.device)
  File "/home/jiyu/miniconda2/envs/py27/lib/python2.7/site-packages/theano/sandbox/gpuarray/__init__.py", line 46, in init_dev
    "Make sure Theano and libgpuarray/pygpu "
RuntimeError: ('Wrong major API version for gpuarray:', 2, 'Make sure Theano and libgpuarray/pygpu are in sync.')

Could you make sure that you are suggesting correct versions of Theano and Pylearn2?
Thanks

**Comment by iamweiweishi** [comment]
from six.moves import input, zip as izip

**Comment by roshan-gopalakrishnan** [comment]
Anybody resolved this issue ?

**Comment by nickfraser** [comment]
The environment for this can be quite tricky to set up, very specific versions of some packages are required.

I project I worked on [BNN-PYNQ](https://github.com/Xilinx/BNN-PYNQ) used slightly modified versions of this BinaryNet repo to train the networks. The dockerfile in that repo and instructions are still (at least the last time I checked) compatible with this project.

I'd recommend the [dockerfiles](https://github.com/Xilinx/BNN-PYNQ/tree/master/bnn/src/training/docker), but you can also try to follow the [instructions](https://github.com/Xilinx/BNN-PYNQ/tree/master/bnn/src/training#installing-the-training-environment) directly as well.
